add(zero,X,X).
add(s(X),Y,s(Z)):-add(X,Y,Z).
mult(zero,X,zero).
mult(X,zero,zero).
mult(s(zero),X,X).
mult(X,s(zero),X).
mult(s(X),Y,Z):-mult(X,Y,T),add(T,Y,Z).
pow(X,s(zero),X).
pow(X,s(Y),Z):-pow(X,Y,T),mult(T,X,Z).
smaller(zero,s(_)).
smaller(s(X),s(Y)):-smaller(X,Y).
?-add(zero,zero,X).
?-add(s(s(zero)),s(zero),X).
?-add(s(s(zero)),s(s(zero)),X).
?-mult(zero,s(s(s(zero))),X).
?-mult(s(zero),s(s(s(zero))),X).
?-mult(s(s(s(zero))),s(s(s(zero))),X).
?-pow(s(s(s(zero))),s(zero),X).
?-pow(s(zero),s(s(s(zero))),X).
?-pow(s(s(zero)),s(s(s(zero))),X).
?-smaller(zero,s(s(zero))).
?-smaller(X,zero).
?-smaller(s(s(zero)),s(zero)).
?-smaller(s(s(zero)),s(s(s(zero)))).
