{<|X -> zero|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>|>}
{<|X -> zero|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>|>, <|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>}|>|>, <|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>}|>|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>|>}
{<|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>, <|X -> <|Compound -> s, Arguments -> {zero}|>|>}
{<|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>|>, <|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>|>, <|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>|>, <|X -> <|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {<|Compound -> s, Arguments -> {zero}|>}|>}|>}|>}|>}|>}|>}|>|>}
